/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace node_registry {
    // Membership half of the placement store: every worker node announces
    // itself here and proves liveness by heartbeat. Object leases will share
    // this store later; today it answers &quot;which nodes are alive and how busy
    // are they&quot;.
    export interface NodeRegistryService {
        // A booting node introduces itself and receives its identity and the
    // cadence it must heartbeat at.
        register(
            data: RegisterNodeRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<NodeRegistration>;
        // Periodic liveness and load report. NOT_FOUND means the node has
    // already aged out and must register again.
        heartbeat(
            data: HeartbeatRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<google.protobuf.Empty>;
        // Every node considered alive right now; the aged-out are gone.
        listNodes(
            data: google.protobuf.Empty,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ListNodesResponse>;
        // One node by id, alive or NOT_FOUND; the address a forwarded object
    // call travels to.
        getNode(
            data: GetNodeRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Node>;
        // Claims one object for one node. A lease lives exactly as long as its
    // holder stays in the registry, so expiry is node age-out; a claim
    // against a dead holder frees it and wins.
        acquireLease(
            data: AcquireLeaseRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Lease>;
        // Releases a lease the node still holds; a rehoming courtesy, never
    // required for correctness.
        releaseLease(
            data: ReleaseLeaseRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<google.protobuf.Empty>;
        // Who holds one object right now, without claiming: dead holders read
    // as unheld. NOT_FOUND when nobody does; how a read finds the node
    // with the freshest copy.
        getLease(
            data: GetLeaseRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Lease>;
        // A graceful shutdown&#x27;s goodbye: deletes the node row immediately,
    // freeing its leases through the same cascade age-out uses, so a
    // deploy never serves a minute of dead forwards while the ttl runs
    // out. Best effort; a crash still ages out.
        deregister(
            data: DeregisterRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<google.protobuf.Empty>;
        // Object identities from the instance directory, which outlives the
    // contracts that declared them; filterable by class and name prefix,
    // always paged, because per-user classes grow with the user table.
        listInstances(
            data: ListInstancesRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ListInstancesResponse>;
        // How many directory identities each class holds, per project: what
    // a console rail shows before anyone asks for actual names.
        countInstances(
            data: CountInstancesRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<CountInstancesResponse>;
        // Mirrors one object&#x27;s armed alarm; setting replaces. Written by the
    // hosting node asynchronously, OFF the call&#x27;s transaction, so a
    // spurious row (a rolled-back arm) only ever costs a wasted wake.
        setAlarm(
            data: SetAlarmRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<google.protobuf.Empty>;
        // Drops one object&#x27;s mirrored alarm; written when it fires or clears.
        clearAlarm(
            data: ClearAlarmRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<google.protobuf.Empty>;
        // Every mirrored alarm due at &#x60;now_ms&#x60;, oldest first: the sweep, as
    // one indexed query any live node can serve. Rows deliberately
    // outlive their holder&#x27;s death; waking is claiming.
        dueAlarms(
            data: DueAlarmsRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<DueAlarmsResponse>;
    }
    export interface ListInstancesRequest {
        projectIds?: string[];
        // Only this class&#x27;s identities; empty lists every class.
        class?: string;
        // Only names starting with this prefix; how a type-ahead picker
    // narrows a class too large to browse. Empty matches everything.
        namePrefix?: string;
        // Rows per page; the server clamps unreasonable values.
        pageSize?: number;
        // Zero-based page over the filtered, (class, name)-ordered rows.
        page?: number;
    }
    export interface CountInstancesRequest {
        projectIds?: string[];
    }
    export interface ClassCount {
        class?: string;
        count?: number;
    }
    export interface CountInstancesResponse {
        // One row per class holding at least one identity, class-ordered.
        counts?: node_registry.ClassCount[];
    }
    export interface ObjectInstance {
        // Identity scope: the project for resource classes. Cron rows scope
    // to their script and never surface in a project listing.
        scopeId?: string;
        class?: string;
        name?: string;
        // Script whose code the object ran when first claimed; directory
    // metadata (&quot;declared by&quot;), never identity.
        scriptId?: string;
        // Unix milliseconds of the first claim.
        createdMs?: number;
    }
    export interface ListInstancesResponse {
        instances?: node_registry.ObjectInstance[];
        // Rows matching the filter across every page, so a picker can say
    // &quot;12,340 more&quot;.
        total?: number;
    }
    export interface GetNodeRequest {
        nodeId?: string;
    }
    export interface AcquireLeaseRequest {
        // blake3 of the object identity, hex.
        objectId?: string;
        nodeId?: string;
        // The identity the hash was made from: (scope, class, name), where
    // the scope is the project for every resource class and the script
    // for &#x60;__cron&#x60; (a schedule belongs to its script, so equal
    // expressions across a project never collide). Recorded in the
    // instance directory so object data stays enumerable after the
    // declaring revision is gone.
        scopeId?: string;
        class?: string;
        name?: string;
        // The owner script whose code the object runs; directory metadata,
    // never part of the identity.
        scriptId?: string;
    }
    export interface Lease {
        objectId?: string;
        // Whoever holds it now: the claimant on success, the incumbent on
    // refusal.
        nodeId?: string;
        acquired?: boolean;
        // Monotonic per-object claim counter; fences storage shipping, so a
    // zombie ex-owner&#x27;s uploads lose to any newer epoch.
        epoch?: number;
    }
    export interface ReleaseLeaseRequest {
        objectId?: string;
        nodeId?: string;
    }
    export interface GetLeaseRequest {
        // blake3 of the object identity, hex.
        objectId?: string;
    }
    export interface DeregisterRequest {
        nodeId?: string;
    }
    export interface SetAlarmRequest {
        // blake3 of the object identity, hex.
        objectId?: string;
        // The object&#x27;s own key (scope/class/name), what a wake needs.
        ownKey?: string;
        // Unix milliseconds the alarm is due at.
        dueMs?: number;
    }
    export interface ClearAlarmRequest {
        objectId?: string;
    }
    export interface DueAlarmsRequest {
        // Alarms with due_ms at or before this instant are due.
        nowMs?: number;
        // Largest batch one sweep asks for; the next sweep drains the rest.
        limit?: number;
    }
    export interface AlarmRow {
        objectId?: string;
        ownKey?: string;
        dueMs?: number;
    }
    export interface DueAlarmsResponse {
        alarms?: node_registry.AlarmRow[];
    }
    export interface RegisterNodeRequest {
        // Where other platform services reach this node&#x27;s WorkerData grpc
    // service, host:port.
        address?: string;
        // Roles the node serves, e.g. &quot;http&quot;; object hosting arrives later.
        capabilities?: string[];
    }
    export interface NodeRegistration {
        nodeId?: string;
        // Missing several of these in a row ages the node out.
        heartbeatIntervalSecs?: number;
    }
    export interface HeartbeatRequest {
        nodeId?: string;
        // Instantaneous load: requests in flight when the beat was sent.
        load?: number;
    }
    export interface Node {
        nodeId?: string;
        address?: string;
        capabilities?: string[];
        load?: number;
        registered?: string;
        lastHeartbeat?: string;
    }
    export interface ListNodesResponse {
        nodes?: node_registry.Node[];
    }
}
export namespace google {
    export namespace protobuf {
        // tslint:disable-next-line:no-empty-interface
        export interface Empty {
        }
    }
}

