/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace node_registry {
    // Membership half of the placement store: every worker node announces
    // itself here and proves liveness by heartbeat. Object leases will share
    // this store later; today it answers &quot;which nodes are alive and how busy
    // are they&quot;.
    export interface NodeRegistryService {
        // A booting node introduces itself and receives its identity and the
    // cadence it must heartbeat at.
        register(
            data: RegisterNodeRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<NodeRegistration>;
        // Periodic liveness and load report. NOT_FOUND means the node has
    // already aged out and must register again.
        heartbeat(
            data: HeartbeatRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<google.protobuf.Empty>;
        // Every node considered alive right now; the aged-out are gone.
        listNodes(
            data: google.protobuf.Empty,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ListNodesResponse>;
    }
    export interface RegisterNodeRequest {
        // Where other platform services reach this node, host:port.
        address?: string;
        // Roles the node serves, e.g. &quot;http&quot;; object hosting arrives later.
        capabilities?: string[];
    }
    export interface NodeRegistration {
        nodeId?: string;
        // Missing several of these in a row ages the node out.
        heartbeatIntervalSecs?: number;
    }
    export interface HeartbeatRequest {
        nodeId?: string;
        // Instantaneous load: requests in flight when the beat was sent.
        load?: number;
    }
    export interface Node {
        nodeId?: string;
        address?: string;
        capabilities?: string[];
        load?: number;
        registered?: string;
        lastHeartbeat?: string;
    }
    export interface ListNodesResponse {
        nodes?: node_registry.Node[];
    }
}
export namespace google {
    export namespace protobuf {
        // tslint:disable-next-line:no-empty-interface
        export interface Empty {
        }
    }
}

