/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace secret_service {
    // Project secrets: versioned, envelope-encrypted at rest, write-only on the
    // management plane. Values leave this service only through ResolveSecret,
    // which workers call when a script declares &#x60;secret &quot;name&quot;&#x60;.
    export interface SecretService {
        // Creates or rotates: always inserts a new immutable version and
    // returns its metadata. There is no in-place update.
        setSecret(
            data: SetSecretRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<SecretMeta>;
        // Tombstones the name: it leaves listings and head resolution, while
    // already-pinned versions keep resolving so running workflows finish
    // with the credentials they started with.
        deleteSecret(
            data: DeleteSecretRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<google.protobuf.Empty>;
        // Names and metadata for the console and CLI; never values.
        listSecrets(
            data: ListSecretsRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ListSecretsResponse>;
        // Plaintext for one secret: the head when version is 0, or exactly the
    // requested version (a workflow replay&#x27;s pin). NOT_FOUND for unknown
    // names, tombstoned heads, and versions that never existed.
        resolveSecret(
            data: ResolveSecretRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ResolvedSecret>;
    }
    export interface SetSecretRequest {
        projectId?: string;
        name?: string;
        // The plaintext value; encrypted before it touches storage and never
    // returned by any management rpc.
        value?: string;
        // User id that performed the write; audit metadata, never identity.
        createdBy?: string;
    }
    export interface DeleteSecretRequest {
        projectId?: string;
        name?: string;
    }
    export interface ListSecretsRequest {
        projectId?: string;
    }
    export interface SecretMeta {
        name?: string;
        // Head version at the time of the call.
        version?: number;
        // Unix milliseconds of the head version&#x27;s write.
        createdMs?: number;
        createdBy?: string;
    }
    export interface ListSecretsResponse {
        // Live (non-tombstoned) names, name-ordered.
        secrets?: secret_service.SecretMeta[];
    }
    export interface ResolveSecretRequest {
        projectId?: string;
        name?: string;
        // 0 resolves the head; a workflow replay passes its pinned version.
        version?: number;
        // Script whose vm asked; audit metadata today, the enforcement point
    // when script.json bindings land, without a proto change.
        scriptId?: string;
    }
    export interface ResolvedSecret {
        value?: string;
        // The version the value came from; what a workflow&#x27;s first resolve pins.
        version?: number;
    }
}
export namespace google {
    export namespace protobuf {
        // tslint:disable-next-line:no-empty-interface
        export interface Empty {
        }
    }
}

