/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace worker_data {
    // The worker&#x27;s data plane, served by every worker node: object method
    // dispatch and typed reads against object storage. This is the only way
    // into an object from outside a vm; the api&#x27;s dashboard calls and
    // worker-to-worker forwards both travel it. Callers authenticate with the
    // cluster-internal token in &#x60;x-actias-internal&#x60; metadata; nothing here is
    // ever reachable from outside the cluster.
    export interface WorkerData {
        // One object method call. The receiving node resolves the owner
    // script&#x27;s current revision itself, so every route into an object
    // runs the same code. Method failures ride the result envelope
    // (they are the object&#x27;s own user-safe errors, addressed to the
    // calling script); a Status means the transport itself failed.
        dispatch(
            data: ObjectCall,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<CallResult>;
        // One typed read against an object&#x27;s storage, no vm: queue stats or
    // message rows, a database or user object&#x27;s overview, or one
    // read-only SQL statement under the script authorizer. Routed to the
    // freshest copy: the local file, else the lease holder&#x27;s node, else
    // the shipped snapshot replica, else null.
        readStats(
            data: ReadRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReadValue>;
        // The queue&#x27;s journal after the &#x60;since&#x60; cursor, oldest first; routed
    // exactly like ReadStats.
        readJournal(
            data: ReadRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReadValue>;
        // Node-grouped connection delivery: one call carries every due
    // stream event for every followed connection this node hosts, and
    // the node fans out to its own sockets. The reply names the
    // connections that are gone so the publisher prunes their edges;
    // everything else advanced regardless (connection edges are
    // at-most-once). Publish cost is nodes listening, never listeners.
        deliverInbox(
            data: InboxBatch,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<InboxReceipts>;
        // Node-grouped delivery for DURABLE followers: the node dispatches
    // __receive to each of its resident follower objects in order and
    // reports how far each got. The follower&#x27;s own receive cursor
    // makes any redelivery skip, so at-least-once stays safe to
    // repeat.
        deliverReceives(
            data: ReceiveBatch,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReceiveReceipts>;
    }
    // Due events for the connections one node hosts.
    export interface InboxBatch {
        entries?: worker_data.ConnectionEvents[];
    }
    export interface ConnectionEvents {
        connection?: string;
        // A json array of {topic, from_class, from_name, data} objects.
        eventsJson?: string;
    }
    export interface InboxReceipts {
        // Connections the node no longer holds; their edges are dead.
        gone?: string[];
    }
    // Due events for the durable followers one node hosts, from one
    // publisher. Small sets ride inline; past the cap only the range
    // travels and the node reads the events from the nearest copy of the
    // publisher&#x27;s log (usually its own replica).
    export interface ReceiveBatch {
        scopeId?: string;
        publisherClass?: string;
        publisherName?: string;
        entries?: worker_data.ReceiveEntry[];
    }
    export interface ReceiveEntry {
        followerClass?: string;
        followerName?: string;
        // Inline: a json array of {seq, topic, from_class, from_name,
    // data}; empty when a range travels instead.
        eventsJson?: string;
        // The range (after, upto], meaningful when events_json is empty.
        rangeAfter?: number;
        rangeUpto?: number;
        topic?: string;
        // The edge&#x27;s filter, json-encoded; empty means unfiltered. Range
    // reads apply it where the events materialize.
        filterJson?: string;
    }
    export interface ReceiveReceipts {
        outcomes?: worker_data.ReceiveOutcome[];
    }
    export interface ReceiveOutcome {
        followerClass?: string;
        followerName?: string;
        // Highest seq whose handler committed; 0 when nothing landed.
        deliveredTo?: number;
        // True when delivery stopped early; the publisher backs the edge
    // off exactly as a per-event failure would have.
        failed?: boolean;
    }
    // What one object call carries: the identity and the call, never code
    // coordinates.
    export interface ObjectCall {
        // The identity scope: the project id (cron objects never travel this
    // transport; their scope is their script).
        scopeId?: string;
        class?: string;
        name?: string;
        method?: string;
        // The call&#x27;s arguments as one json array; user method arguments are
    // arbitrary values, so they stay json on the wire.
        argumentsJson?: string;
        // The object-call stack this call rides on, target included when the
    // sender already extended it; what makes cycles refusable.
        chain?: string[];
        // The producing script&#x27;s identity, carried across hops; absent for
    // dashboard dispatches, which have no script behind them.
        caller?: worker_data.Caller;
        // True when the caller is not a worker: a first hop may forward once
    // to the lease holder. Worker-to-worker calls arrive with the hop
    // already spent, so a stale lease view can never bounce a call
    // between nodes.
        firstHop?: boolean;
    }
    // The calling script&#x27;s identity as it travels between nodes.
    export interface Caller {
        // Public identifier, the name a human recognizes.
        script?: string;
        // Revision id the caller executed as.
        revision?: string;
    }
    // One dispatched call&#x27;s outcome.
    export interface CallResult {
        // The method&#x27;s return value, json-encoded; meaningful only when
    // &#x60;error&#x60; is empty.
        resultJson?: string;
        // The call&#x27;s failure exactly as the object&#x27;s runtime produced it,
    // user-safe; empty on success.
        error?: string;
        // Set when this node does not hold the object: the caller&#x27;s view of
    // the home is stale, and it should re-resolve instead of retrying
    // here. &#x60;error&#x60; still carries a message for logs.
        wrongHome?: boolean;
    }
    // What one read asks for; ReadStats and ReadJournal share it because
    // both name an object and route the same way.
    export interface ReadRequest {
        // The identity scope: the project id.
        scopeId?: string;
        class?: string;
        name?: string;
        // One read-only SQL statement under the same authorizer script SQL
    // runs with, instead of the class&#x27;s typed overview (ReadStats only).
        sql?: string;
        // The queue&#x27;s live and dead message rows instead of its stats
    // summary (ReadStats only, queue class only).
        messages?: boolean;
        // Journal cursor: rows strictly after this id (ReadJournal only).
        since?: number;
        // True when the caller is not a worker: a first hop may forward once
    // to the lease holder for the freshest copy. A forwarded read
    // answers from what its node has and never forwards again.
        firstHop?: boolean;
        // The publisher&#x27;s edge table plus its event-log head instead of the
    // class&#x27;s overview (ReadStats only): the console&#x27;s followers panel.
        followers?: boolean;
    }
    // One read&#x27;s answer.
    export interface ReadValue {
        // The value, json-encoded; &#x60;null&#x60; when the object has no observable
    // state anywhere (nothing local, nothing ever shipped), which reads
    // as empty, not as an error.
        valueJson?: string;
    }
}

