/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace worker_data {
    // The worker&#x27;s data plane, served by every worker node: object method
    // dispatch and typed reads against object storage. This is the only way
    // into an object from outside a vm; the api&#x27;s dashboard calls and
    // worker-to-worker forwards both travel it. Callers authenticate with the
    // cluster-internal token in &#x60;x-actias-internal&#x60; metadata; nothing here is
    // ever reachable from outside the cluster.
    export interface WorkerData {
        // One object method call. The receiving node resolves the owner
    // script&#x27;s current revision itself, so every route into an object
    // runs the same code. Method failures ride the result envelope
    // (they are the object&#x27;s own user-safe errors, addressed to the
    // calling script); a Status means the transport itself failed.
        dispatch(
            data: ObjectCall,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<CallResult>;
        // One typed read against an object&#x27;s storage, no vm: queue stats or
    // message rows, a database or user object&#x27;s overview, or one
    // read-only SQL statement under the script authorizer. Routed to the
    // freshest copy: the local file, else the lease holder&#x27;s node, else
    // the shipped snapshot replica, else null.
        readStats(
            data: ReadRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReadValue>;
        // The queue&#x27;s journal after the &#x60;since&#x60; cursor, oldest first; routed
    // exactly like ReadStats.
        readJournal(
            data: ReadRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReadValue>;
    }
    // What one object call carries: the identity and the call, never code
    // coordinates.
    export interface ObjectCall {
        // The identity scope: the project id (cron objects never travel this
    // transport; their scope is their script).
        scopeId?: string;
        class?: string;
        name?: string;
        method?: string;
        // The call&#x27;s arguments as one json array; user method arguments are
    // arbitrary values, so they stay json on the wire.
        argumentsJson?: string;
        // The object-call stack this call rides on, target included when the
    // sender already extended it; what makes cycles refusable.
        chain?: string[];
        // The producing script&#x27;s identity, carried across hops; absent for
    // dashboard dispatches, which have no script behind them.
        caller?: worker_data.Caller;
        // True when the caller is not a worker: a first hop may forward once
    // to the lease holder. Worker-to-worker calls arrive with the hop
    // already spent, so a stale lease view can never bounce a call
    // between nodes.
        firstHop?: boolean;
    }
    // The calling script&#x27;s identity as it travels between nodes.
    export interface Caller {
        // Public identifier, the name a human recognizes.
        script?: string;
        // Revision id the caller executed as.
        revision?: string;
    }
    // One dispatched call&#x27;s outcome.
    export interface CallResult {
        // The method&#x27;s return value, json-encoded; meaningful only when
    // &#x60;error&#x60; is empty.
        resultJson?: string;
        // The call&#x27;s failure exactly as the object&#x27;s runtime produced it,
    // user-safe; empty on success.
        error?: string;
    }
    // What one read asks for; ReadStats and ReadJournal share it because
    // both name an object and route the same way.
    export interface ReadRequest {
        // The identity scope: the project id.
        scopeId?: string;
        class?: string;
        name?: string;
        // One read-only SQL statement under the same authorizer script SQL
    // runs with, instead of the class&#x27;s typed overview (ReadStats only).
        sql?: string;
        // The queue&#x27;s live and dead message rows instead of its stats
    // summary (ReadStats only, queue class only).
        messages?: boolean;
        // Journal cursor: rows strictly after this id (ReadJournal only).
        since?: number;
        // True when the caller is not a worker: a first hop may forward once
    // to the lease holder for the freshest copy. A forwarded read
    // answers from what its node has and never forwards again.
        firstHop?: boolean;
    }
    // One read&#x27;s answer.
    export interface ReadValue {
        // The value, json-encoded; &#x60;null&#x60; when the object has no observable
    // state anywhere (nothing local, nothing ever shipped), which reads
    // as empty, not as an error.
        valueJson?: string;
    }
}

