/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace worker_data {
    // The worker&#x27;s data plane, served by every worker node: object method
    // dispatch and typed reads against object storage. This is the only way
    // into an object from outside a vm; the api&#x27;s dashboard calls and
    // worker-to-worker forwards both travel it. Callers authenticate with the
    // cluster-internal token in &#x60;x-actias-internal&#x60; metadata; nothing here is
    // ever reachable from outside the cluster.
    export interface WorkerData {
        // One object method call. The receiving node resolves the owner
    // script&#x27;s current revision itself, so every route into an object
    // runs the same code. Method failures ride the result envelope
    // (they are the object&#x27;s own user-safe errors, addressed to the
    // calling script); a Status means the transport itself failed.
        dispatch(
            data: ObjectCall,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<CallResult>;
        // One shell chunk, run in a fresh vm on this node under the session&#x27;s
    // grants: the operator&#x27;s principal binds what the api says the
    // operator may open. Prints come back with the value; a failure is
    // the chunk&#x27;s own error, addressed to the person typing.
        runShell(
            data: ShellRun,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ShellOutcome>;
        // One typed read against an object&#x27;s storage, no vm: queue stats or
    // message rows, a database or user object&#x27;s overview, or one
    // read-only SQL statement under the script authorizer. Routed to the
    // freshest copy: the local file, else the lease holder&#x27;s node, else
    // the shipped snapshot replica, else null.
        readStats(
            data: ReadRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReadValue>;
        // The queue&#x27;s journal after the &#x60;since&#x60; cursor, oldest first; routed
    // exactly like ReadStats.
        readJournal(
            data: ReadRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReadValue>;
        // Node-grouped connection delivery: one call carries every due
    // stream event for every followed connection this node hosts, and
    // the node fans out to its own sockets. The reply names the
    // connections that are gone so the publisher prunes their edges;
    // everything else advanced regardless (connection edges are
    // at-most-once). Publish cost is nodes listening, never listeners.
        deliverInbox(
            data: InboxBatch,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<InboxReceipts>;
        // Node-grouped delivery for DURABLE followers: the node dispatches
    // __receive to each of its resident follower objects in order and
    // reports how far each got. The follower&#x27;s own receive cursor
    // makes any redelivery skip, so at-least-once stays safe to
    // repeat.
        deliverReceives(
            data: ReceiveBatch,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReceiveReceipts>;
        // One listing over a class&#x27;s directory: the rows every object in
    // the class contributes, answered from the node&#x27;s own overlay of
    // the class&#x27;s base and deltas. No object is woken and no lease is
    // taken; the answer trails each object&#x27;s last settled write.
        listDirectory(
            data: DirectoryQuery,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<DirectoryPage>;
        // The verified read: the same query, with every candidate checked
    // against its object&#x27;s own shipping manifest before it is served.
    // A row that stopped matching is dropped, a fresher row is served
    // fresh, and a row that cannot be checked is returned FLAGGED
    // rather than dropped, because a lost row is the one failure the
    // directory refuses. Still no waking and no leases: the common
    // case costs one small manifest read per candidate, never a
    // restore. Limit bounds candidates EXAMINED, so a page may return
    // fewer entries than asked plus a cursor.
        visitDirectory(
            data: DirectoryQuery,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<VisitPage>;
        // Rebuilds one class&#x27;s index from the placement store&#x27;s live
    // identities and each object&#x27;s shipping manifest, waking nothing.
    // 
    // Background reconciliation discovers classes by listing the
    // store, so a class whose prefix is gone entirely cannot be found
    // at all: nothing names it. A name can always be asked for, which
    // is why total loss is an operator&#x27;s verb rather than a timer&#x27;s
    // job.
        rebuildDirectory(
            data: DirectoryRebuild,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<DirectoryRebuilt>;
        // Tail replication. The lease holder appends its committed WAL
    // prefix to K replica nodes as it ships it, and a written call is
    // answered once Q of them have it durably; the blob store keeps
    // shipping behind the answer. A replica appends bytes at an offset
    // and checks a fence; it never interprets them. A duplicate at an
    // offset it already holds is acked, a gap is refused with the
    // length it does hold so the owner resends from there, and an
    // epoch below its fence is refused outright.
        appendWal(
            data: WalAppend,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<WalAppended>;
        // What a replica holds for one generation, raising its fence to
    // &#x60;fence_to&#x60; first: a takeover at epoch e+1 asks every replica the
    // manifest names, and once Q have answered, an owner at e can never
    // assemble Q acks again.
        replicaState(
            data: ReplicaQuery,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReplicaInfo>;
        // The replica&#x27;s copy, base then WAL, in chunks: what a takeover lays
    // down instead of restoring from the store.
        fetchReplica(
            data: ReplicaQuery,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ReplicaChunk>;
        // What the owner has answered to callers so far for one object: the
    // generation and the WAL length its last released flight reached. A
    // replica serves a read from its own copy only once the copy has
    // reached this, so a read on any node sees every write a caller was
    // told succeeded, without any token crossing requests.
        watermark(
            data: WatermarkQuery,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<WatermarkInfo>;
        // A generation start: the owner lays a base on the replica as a
    // stream of parts, a header naming the chunk list and then the
    // chunks the replica lacks. A replica on the header&#x27;s previous list
    // is sent only the chunks a rotation dirtied and patches its base in
    // place; one that is not answers NO_BASE and is sent every chunk.
        layGeneration(
            data: Observable<GenerationPart>,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<WalAppended>;
        // The live connections a project holds, both directions. The node
    // asked answers for itself and, unless &#x60;local_only&#x60;, asks every
    // other live node the same question, so one call lists the cluster.
        listConnections(
            data: ConnectionQuery,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ConnectionList>;
    }
    export interface ConnectionQuery {
        // Empty lists every project&#x27;s; the api always names one.
        projectId?: string;
        localOnly?: boolean;
    }
    export interface ConnectionRow {
        id?: string;
        // The declared connection class running the wire.
        connectionClass?: string;
        // The identity it speaks as.
        class?: string;
        name?: string;
        // &quot;inbound&quot; (a client&#x27;s upgrade) or &quot;outbound&quot; (dialled by the project).
        direction?: string;
        // The far side&#x27;s host, outbound only.
        peer?: string;
        node?: string;
        projectId?: string;
        scriptId?: string;
        openedAtMs?: number;
        // &quot;new&quot;, &quot;warm&quot; or &quot;hibernated&quot;.
        status?: string;
        follows?: number;
    }
    export interface ConnectionList {
        connections?: worker_data.ConnectionRow[];
    }
    export interface WatermarkQuery {
        objectId?: string;
    }
    export interface WatermarkInfo {
        // False when this node does not hold the object resident.
        held?: boolean;
        // The residency&#x27;s lease epoch, whether or not a flight has released.
        epoch?: number;
        base?: number;
        // WAL bytes the owner&#x27;s last released flight reached.
        length?: number;
        // False until the residency&#x27;s first flight has released: no copy
    // anywhere can be vouched for before that, and a reader forwards.
        released?: boolean;
    }
    export interface WalAppend {
        objectId?: string;
        // The owner&#x27;s lease epoch and the generation&#x27;s base index; together
    // they name the WAL these bytes belong to.
        epoch?: number;
        base?: number;
        // Byte offset in the generation&#x27;s WAL these bytes start at.
        offset?: number;
        bytes?: Uint8Array;
        // How far the store&#x27;s manifest covers this WAL; informational, for
    // eviction.
        covered?: number;
    }
    export interface GenerationPart {
        header?: worker_data.GenerationHeader;
        chunk?: worker_data.GenerationChunk;
        done?: worker_data.GenerationDone;
    }
    export interface GenerationHeader {
        objectId?: string;
        epoch?: number;
        base?: number;
        // The hash of the chunk list this delta applies to, hex; empty when
    // every chunk follows.
        fromList?: string;
        // The base file&#x27;s length after the lay.
        baseLen?: number;
        // The new generation&#x27;s chunk list: one blake3 hex per CHUNK_BYTES
    // of the base, in order.
        chunks?: string[];
    }
    export interface GenerationChunk {
        // Which range of the base these bytes are; the last chunk is short.
        index?: number;
        bytes?: Uint8Array;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface GenerationDone {
    }
    export interface WalAppended {
        // The WAL length the replica holds after the call.
        length?: number;
        // True when the bytes were appended (or already held). False with
    // &#x60;refusal&#x60; set: a gap (resend from &#x60;length&#x60;), a missing generation
    // (resend with the base), or a fence.
        applied?: boolean;
        refusal?: string;
    }
    export interface ReplicaQuery {
        objectId?: string;
        epoch?: number;
        base?: number;
        // Raise the replica&#x27;s fence to this epoch before answering; 0
    // leaves it.
        fenceTo?: number;
    }
    export interface ReplicaInfo {
        // Whether the replica holds this generation at all.
        held?: boolean;
        length?: number;
        fence?: number;
    }
    export interface ReplicaChunk {
        // Base bytes come first, then WAL bytes; a chunk carries one kind.
        base?: Uint8Array;
        wal?: Uint8Array;
    }
    export interface DirectoryRebuild {
        scopeId?: string;
        class?: string;
    }
    export interface DirectoryRebuilt {
        // Identities the placement store still lists as live.
        live?: number;
        // Rows recovered from manifests.
        rows?: number;
        // Live objects whose manifest carries no row yet. Not an error:
    // nothing has settled to copy, and a backfill is what covers them.
        withoutRow?: number;
        // Rows retired because the object no longer exists.
        tombstones?: number;
        // Whether this node did the work. False means another node holds
    // the class&#x27;s lease and is rebuilding it already.
        held?: boolean;
    }
    // A predicate over one directory field. Values are json-encoded so one
    // shape carries every kind a field may hold, arrays included.
    export interface DirectoryCondition {
        // Field name as the class&#x27;s directory function returned it; nested
    // tables arrive flattened, so &quot;location.region&quot; is one field.
        field?: string;
        // &quot;eq&quot;, &quot;ne&quot;, &quot;lt&quot;, &quot;lte&quot;, &quot;gt&quot;, &quot;gte&quot;, &quot;one_of&quot;, &quot;starts_with&quot;,
    // &quot;contains&quot;, &quot;exists&quot;. One_of rather than in, because &#x60;in&#x60; is a
    // lua keyword and the wire uses the word the author types. Unknown
    // operators are refused rather than ignored, so a newer caller
    // never silently loses a filter.
        op?: string;
        // The operand, json-encoded: a scalar, an array for one_of, or a
    // boolean for &quot;exists&quot;.
        valueJson?: string;
    }
    // A conjunction of conditions, with nested combinators. The tree is
    // carried rather than a query string: the worker translates it into
    // parameterized sql, so no caller can shape an identifier.
    export interface DirectoryWhere {
        conditions?: worker_data.DirectoryCondition[];
        // OR over sub-wheres.
        any?: worker_data.DirectoryWhere[];
        // Explicit AND, for grouping inside an &#x60;any&#x60;.
        all?: worker_data.DirectoryWhere[];
        // NOT over sub-wheres.
        none?: worker_data.DirectoryWhere[];
    }
    export interface DirectoryOrder {
        field?: string;
        descending?: boolean;
    }
    export interface DirectoryQuery {
        // The project the class belongs to.
        scopeId?: string;
        class?: string;
        where?: worker_data.DirectoryWhere;
        order?: worker_data.DirectoryOrder[];
        // Rows this page may carry; the worker caps it.
        limit?: number;
        // From a previous page; absent starts at the beginning.
        cursor?: string;
    }
    // One object&#x27;s row.
    export interface DirectoryEntry {
        name?: string;
        objectId?: string;
        // Field name to json-encoded value, for the fields the class
    // exposes and this object has.
        fields?: { [key: string]: string };
    }
    // One verified candidate. Verified entries carry the object&#x27;s settled
    // row (which may be fresher than what the index held); flagged entries
    // carry the indexed row and say why it could not be checked.
    export interface VisitEntry {
        entry?: worker_data.DirectoryEntry;
        // The row could not be verified; it is served anyway, saying so,
    // because dropping it would manufacture the false negative the
    // directory exists to refuse.
        unverified?: boolean;
        // Why, when unverified; empty otherwise.
        reason?: string;
    }
    export interface VisitPage {
        entries?: worker_data.VisitEntry[];
        // Continues where this page&#x27;s CANDIDATES ended: verification may
    // drop rows, so a short page with a cursor is normal, not the end.
        cursor?: string;
        // Same contract as DirectoryPage.building.
        building?: string[];
    }
    export interface DirectoryPage {
        entries?: worker_data.DirectoryEntry[];
        // Feeds the next query; absent on the last page.
        cursor?: string;
        // Fields still building, if any. A query naming one is refused
    // outright; this reports the rest so a console can show progress
    // rather than leaving a column mysteriously missing.
        building?: string[];
    }
    // Due events for the connections one node hosts. The events ride
    // once per batch; each edge names the slice it gets, so the payload
    // never multiplies by listeners.
    export interface InboxBatch {
        // A json array of {seq, topic, from_class, from_name, data}
    // objects, in publish order.
        eventsJson?: string;
        edges?: worker_data.InboxEdge[];
    }
    // One followed connection&#x27;s slice of the batch.
    export interface InboxEdge {
        connection?: string;
        topic?: string;
        // Events at or below this seq were already heard.
        after?: number;
        // Empty forwards everything on the topic; anything else is a json
    // object matched against event data.
        filterJson?: string;
    }
    export interface InboxReceipts {
        // Connections the node no longer holds; their edges are dead.
        gone?: string[];
    }
    // Due events for the durable followers one node hosts, from one
    // publisher. Small sets ride inline; past the cap only the range
    // travels and the node reads the events from the nearest copy of the
    // publisher&#x27;s log (usually its own replica).
    export interface ReceiveBatch {
        scopeId?: string;
        publisherClass?: string;
        publisherName?: string;
        entries?: worker_data.ReceiveEntry[];
    }
    export interface ReceiveEntry {
        followerClass?: string;
        followerName?: string;
        // Inline: a json array of {seq, topic, from_class, from_name,
    // data}; empty when a range travels instead.
        eventsJson?: string;
        // The range (after, upto], meaningful when events_json is empty.
        rangeAfter?: number;
        rangeUpto?: number;
        topic?: string;
        // The edge&#x27;s filter, json-encoded; empty means unfiltered. Range
    // reads apply it where the events materialize.
        filterJson?: string;
    }
    export interface ReceiveReceipts {
        outcomes?: worker_data.ReceiveOutcome[];
    }
    export interface ReceiveOutcome {
        followerClass?: string;
        followerName?: string;
        // Highest seq whose handler committed; 0 when nothing landed.
        deliveredTo?: number;
        // True when delivery stopped early; the publisher backs the edge
    // off exactly as a per-event failure would have.
        failed?: boolean;
    }
    // What one object call carries: the identity and the call, never code
    // coordinates.
    export interface ObjectCall {
        // The identity scope: the project id (cron objects never travel this
    // transport; their scope is their script).
        scopeId?: string;
        class?: string;
        name?: string;
        method?: string;
        // The call&#x27;s arguments as one json array; user method arguments are
    // arbitrary values, so they stay json on the wire.
        argumentsJson?: string;
        // The object-call stack this call rides on, target included when the
    // sender already extended it; what makes cycles refusable.
        chain?: string[];
        // The producing script&#x27;s identity, carried across hops; absent for
    // dashboard dispatches, which have no script behind them.
        caller?: worker_data.Caller;
        // True when the caller is not a worker: a first hop may forward once
    // to the lease holder. Worker-to-worker calls arrive with the hop
    // already spent, so a stale lease view can never bounce a call
    // between nodes.
        firstHop?: boolean;
    }
    // The calling script&#x27;s identity as it travels between nodes.
    export interface Caller {
        // Public identifier, the name a human recognizes.
        script?: string;
        // Revision id the caller executed as.
        revision?: string;
    }
    // One dispatched call&#x27;s outcome.
    // A shell chunk and what it may bind. The grants stand in for a
    // contract: a shell session publishes nothing, so the api derives them
    // from what the project holds and the operator may open.
    export interface ShellRun {
        scopeId?: string;
        // The chunk, as typed or pasted; its return value is the result.
        source?: string;
        kv?: string[];
        databases?: string[];
        objects?: string[];
        // Wall budget for the run; the node caps it.
        wallSecs?: number;
        // Whether the session may write. A read-only chunk still runs: the
    // vm refuses kv set/delete, database exec and method calls inside
    // it, which is what makes an ad hoc join safe to type without
    // ceremony.
        write?: boolean;
    }
    export interface ShellOutcome {
        // The chunk&#x27;s return value as json; &quot;null&quot; for nothing.
        valueJson?: string;
        // Every print and log line, in order.
        output?: string[];
        // The chunk&#x27;s own error, when it failed.
        error?: string;
        // Work units and milliseconds the run consumed.
        work?: number;
        wallMs?: number;
    }
    export interface CallResult {
        // The method&#x27;s return value, json-encoded; meaningful only when
    // &#x60;error&#x60; is empty.
        resultJson?: string;
        // The call&#x27;s failure exactly as the object&#x27;s runtime produced it,
    // user-safe; empty on success.
        error?: string;
        // Set when this node does not hold the object: the caller&#x27;s view of
    // the home is stale, and it should re-resolve instead of retrying
    // here. &#x60;error&#x60; still carries a message for logs.
        wrongHome?: boolean;
    }
    // What one read asks for; ReadStats and ReadJournal share it because
    // both name an object and route the same way.
    export interface ReadRequest {
        // The identity scope: the project id.
        scopeId?: string;
        class?: string;
        name?: string;
        // One read-only SQL statement under the same authorizer script SQL
    // runs with, instead of the class&#x27;s typed overview (ReadStats only).
        sql?: string;
        // The queue&#x27;s live and dead message rows instead of its stats
    // summary (ReadStats only, queue class only).
        messages?: boolean;
        // Journal cursor: rows strictly after this id (ReadJournal only).
        since?: number;
        // True when the caller is not a worker: a first hop may forward once
    // to the lease holder for the freshest copy. A forwarded read
    // answers from what its node has and never forwards again.
        firstHop?: boolean;
        // The publisher&#x27;s edge table plus its event-log head instead of the
    // class&#x27;s overview (ReadStats only): the console&#x27;s followers panel.
        followers?: boolean;
        // The object&#x27;s reserved state pairs instead of the class&#x27;s overview
    // (ReadStats only): the console&#x27;s State tab. The pairs are denied to
    // &#x60;sql&#x60; by the authorizer, so this is their only read.
        state?: boolean;
    }
    // One read&#x27;s answer.
    export interface ReadValue {
        // The value, json-encoded; &#x60;null&#x60; when the object has no observable
    // state anywhere (nothing local, nothing ever shipped), which reads
    // as empty, not as an error.
        valueJson?: string;
    }
}

