[workspace]
resolver = "3"

members = [
    "actias-worker",
    "actias-worker-core",
    "actias-common",
    "actias-declarations",
    "actias-script-service",
    "actias-cli",
    "actias-kv",
]

[workspace.dependencies]
actias-common = { path = "./actias-common" }
blake3 = "1.8.6"
tokio = { version = "1.23.0", features = ["full"] }
tonic = "0.13.0"
prost = "0.13.5"
tonic-build = "0.13.0"
prost-build = "0.13.5"
