[workspace]
members = [
    "ephermal-worker",
    "ephermal-common",
    "ephermal-script-service"
]

[workspace.dependencies]
ephermal-common = { path = "./ephermal-common" }
hyper = { version = "0.14.23", features = ["full"] }
tokio = { version = "1.23.0", features = ["full"] }
tonic = "0.8"
prost = "0.11"
tonic-build = "0.8"
prost-build = "0.11.5"
