[package]
name = "ephermal-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
dotenv = "0.15.0"
tracing = "0.1"
tracing-subscriber = "0.3.16"