[package]
name = "ephermal-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.3.1"
actix-web = "4"
tracing = "0.1"
tracing-subscriber = "0.3.16"