FROM node:22-bookworm-slim

WORKDIR /app

RUN apt update && apt install -y python3 build-essential

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

CMD [ "npx", "mikro-orm", "migration:up" ]

LABEL org.opencontainers.image.source="https://github.com/jsh32/actias"
