-- All types of resources that can be owned/accessed.
CREATE TYPE resource_type AS ENUM ('script');

-- Users table, stores user sign in data.
CREATE TABLE users
(
    id         UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    email      VARCHAR(320) NOT NULL UNIQUE,
    username   VARCHAR(36)  NOT NULL UNIQUE,
    admin      BOOLEAN      NOT NULL DEFAULT false -- System admin.
);

CREATE TYPE auth_method AS ENUM (
    'password',
    'google',
    'github'
);

CREATE TABLE user_auth_methods
(
    id              UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE PRIMARY KEY,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    user_id         UUID        NOT NULL,
    cached_username TEXT        NOT NULL,
    auth_method     auth_method NOT NULL,
    value           TEXT        NOT NULL,
    last_accessed   TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (auth_method, user_id), -- Only one auth method of the same type per user.
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Projects which contain resources
CREATE TABLE projects
(
    id                  UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE PRIMARY KEY,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    name                VARCHAR(32)  NOT NULL,
    owner_id            UUID         NOT NULL,
    default_permissions int          NOT NULL, -- Default bitfield.

    FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Individual resources which exist within a project.
CREATE TABLE resources
(
    id            UUID         NOT NULL UNIQUE PRIMARY KEY, -- This is generated by services, no default
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    resource_type resource_type NOT NULL,
    project_id    UUID          NOT NULL,

    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

-- Access control table per user per resource type.
CREATE TABLE access
(
    id                  UUID         NOT NULL UNIQUE PRIMARY KEY, -- This is generated by services, no default
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    user_id             UUID  NOT NULL,
    project_id          UUID  NOT NULL,
    permission_bitfield int   NOT NULL,

    -- Only one access record per user per project.
    UNIQUE (user_id, project_id),
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
