/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace bundle {
    // A revision&#x27;s content: the entry point plus every file in the bundle.
    export interface Bundle {
        entryPoint?: string;
        files?: bundle.File[];
    }
    // One file in a bundle.
    export interface File {
        revisionId?: string;
        fileName?: string;
        filePath?: string;
        content?: Uint8Array;
    }
}

