/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace bundle {
  export interface Bundle {
    entryPoint?: string;
    // File path name and file content
    files?: bundle.File[];
  }
  export interface File {
    revisionId?: string;
    fileName?: string;
    filePath?: string;
    content?: Uint8Array;
  }
}
