[package]
name = "actias-secret-service"
version.workspace = true
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
actias-common = { workspace = true, features = ["otel"] }
sea-orm = { version = "1.1", default-features = false, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }

prost = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }

aes-gcm = "0.11.0"
base64 = "0.23.1"
getrandom = "0.3"
zeroize = "1"

[build-dependencies]
tonic-build = { workspace = true }
prost-build = { workspace = true }

[dev-dependencies]
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
